### ISSUE TITLE
Update documentation files

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#131]
Just run `./calypso.rb docs build` as it's pretty outdated. But could be perfect if it will make #33 happen.

**Comment by bonkey** [comment]
@hani-ibrahim If you want to start a day with a quick win and feel yourself, how the whole process works – it's great for you.

**Comment by bonkey** [comment]
@hani-ibrahim To be closed, right?

**Comment by hani-ibrahim** [comment]
yea 👍
