### ISSUE TITLE
Sort size list

### ISSUE THREAD

**Issue by hani-ibrahim** [zalando-incubator/atlas-ios#139]
Sizes should be sorted at least when all of them are numbers

**Comment by bonkey** [comment]
Waiting to be implemented on backend side.

**Comment by bonkey** [comment]
AFAIK done

**Comment by hani-ibrahim** [comment]
@bonkey  I don't think so 😟

**Comment by bonkey** [comment]
But seems like they're...

<img width="1000" alt="screens" src="https://cloud.githubusercontent.com/assets/39100/21773928/13de04a0-d691-11e6-9e04-8506588b6434.png">

**Comment by hani-ibrahim** [comment]
yes it's fixed but I didn't know https://github.bus.zalan.do/Atlas/catalog-api/issues/70
