### ISSUE TITLE
raphael.koch@zalando.de on build #180: PayPal Order after pressing "Buy". 
Redirect to PayPal is…

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#157]
Feedback from raphael.koch@zalando.de : PayPal Order after pressing "Buy". 
Redirect to PayPal is missing.

Best,
Raphael :)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57a305cb34a9450100595b71/57bbbc30fa2a050100ccd80b/9cbb0f0f-ad19-423b-a8b3-d9a93294aa25.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Aug 23 2016 07:39:52 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>20160823.180</td></tr><tr><td>App uptime</td><td>159.543</td></tr><tr><td>Build</td><td>180</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Raphaels iPhone 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>96% Unplugged</td></tr><tr><td>Memory free</td><td>52 MB / 3182 MB</td></tr><tr><td>Disk free</td><td>3595 MB / 56981 MB</td></tr><tr><td>Network IP</td><td>10.161.57.28</td></tr></table>

 [Link to buddybuild feedback from build 180](https://dashboard.buddybuild.com/apps/57a305cb34a9450100595b71/feedback?fid=57bbfdc87941a101001eaa24&bnum=180)

**Comment by ahmed-shehata** [comment]
Fixed in https://github.com/zalando-incubator/atlas-ios/issues/156
