### ISSUE TITLE
Zero warnings

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#172]
Please guys, let's get rid of all the warnings again.

**Comment by hani-ibrahim** [comment]
for line length, currently we are solving it by splitting one command over 2 lines, like the example below which doesn't solve the problem
```
let doneButton = UIBarButtonItem(title: loc("Done"), style: UIBarButtonItemStyle.Plain,
            target: self, action: #selector(PaymentProcessingViewController.doneButtonTapped(_:)))
```
This do prevent the warning but not the benefit behind it which prevent too long lines

So we either get rid of this rule or really solve the issue, I would recommend deleting this rule

**Comment by bonkey** [comment]
Well, let's first define this problem, then.

For me long lines first decrease **readability**, second are indicators of rough code.

Or the shorter line is, the code is more declarative, has less raw meat and fewer repetitions.

So, the example you provided could be improved like this:

```(swift)
let doneButton = UIBarButtonItem(title: loc("Done"), style: .Plain, target: self, action: .doneButtonTapped)

private extension Selector {

    static let doneButtonTapped = #selector(PaymentProcessingViewController.doneButtonTapped(_:))

}
```

Or/and create small helper method / extension / whatever:

```
let doneButton = buttonItem("Done", .doneButtonTapped)

func buttonItem(title: String, style: UIBarButtonItemStyle = .Plain, target: NSObject = self, action: Selector) -> UIBarButtonItem {
return UIBarButtonItem(title: loc(title), style: style, target: target, action: action)
}
```

But even without all this extras, the like splitted in the correct place, or for example as:

```
let doneButton = UIBarButtonItem(title: loc("Done"),
    style: UIBarButtonItemStyle.Plain,
    target: self,
    action: #selector(PaymentProcessingViewController.doneButtonTapped(_:)))
```

is again more **readable** than a long line automatically wrapped by Xcode.

**Comment by hani-ibrahim** [comment]
I like your solutions :)

but what about functions as this one
```
    func presentationControllerForPresentedViewController(presented: UIViewController,
        presentingViewController presenting: UIViewController,
        sourceViewController source: UIViewController) -> UIPresentationController? {
        return CheckoutPresentationController(presentedViewController: presented, presentingViewController: presenting)
    }
```

this is an Apple function that's can't be modified and it looks like mixing the function declaration with the body as both are at the same indentation

**note**
Since it's apple method, then long line it not a bad thing 😛 , but you do have a valid point about rough code 😉

**Comment by bonkey** [comment]
You should stop to believe in Apple's infallibility, otherwise you should start coding fat-view-controllers, like [they do](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewController_Class/) (hint: see how many protocols this standard framework class conforms)

**Comment by bonkey** [comment]
And for long methods: probably none of them would exceed 118 chars of argument name and value (20 left for 5 levels of indentation, 2 for `: `)

**Comment by hani-ibrahim** [comment]
that's one of the reasons I don't use `UITableViewController` :D
