### ISSUE TITLE
askUserToLogin: no Login WebView in case of navigation controller absence.

### ISSUE THREAD

**Issue by artdaw** [zalando-incubator/atlas-ios#189]
If customer has a ViewController not wrapped into any kind of NavigationController Login WebView will not open, cause `sourceApp.navigationController?` is nil, see https://github.com/zalando-incubator/atlas-ios/blob/8d8d0c5ad3822700845bcc160db8d1486e360bd7/AtlasSDK/AtlasSDK/APIRequestBuilder.swift#L73. 
I'd propose to change the line of code mentioned to the following:

`sourceApp.presentViewController(navigationController, animated: true, completion: nil)`

**Comment by bonkey** [comment]
Shouldn't it just use `UIApplication.topViewController()`?

**Comment by bonkey** [comment]
Ah, `sourceApp` **is** `UIApplication.topViewController()`. Should be renamed and then used like you suggested.
