### ISSUE TITLE
raphael.koch@zalando.de on build #315: Bug ?

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#200]
Feedback from raphael.koch@zalando.de : Bug ?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57a305cb34a9450100595b71/57c8eb3299745501009a7ca3/754a5fef-bc35-4531-93d0-257105031752.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Sep 02 2016 10:04:36 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>20160902.315</td></tr><tr><td>App uptime</td><td>46.73862</td></tr><tr><td>Build</td><td>315</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Raphaels iPhone 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>93% Unplugged</td></tr><tr><td>Memory free</td><td>89 MB / 3199 MB</td></tr><tr><td>Disk free</td><td>2813 MB / 56981 MB</td></tr><tr><td>Network IP</td><td>10.161.57.72</td></tr></table>

 [Link to buddybuild feedback from build 315](https://dashboard.buddybuild.com/apps/57a305cb34a9450100595b71/feedback?fid=57c94eb4495cbb0100e89696&bnum=315)

**Comment by bonkey** [comment]
@ahmed-shehata you mentioned it's something you need to check, I assigned myself only because I wanted to format errors.

**Comment by ahmed-shehata** [comment]
I think this is already fixed? Please correct me, I cannot replicated it now

**Comment by bonkey** [comment]
@ahmed-shehata Raphael won't get this question. I guess you need to solve it with him somehow.
