### ISSUE TITLE
Chosen payment method is not displayed or even not stored

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#203]
Feedback from raphael.koch@zalando.de : Chosen payment method is not displayed or even not stored

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57a305cb34a9450100595b71/57c8eb3299745501009a7ca3/082e144f-86a3-4c52-bd0e-d5423d5ab747.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Sep 02 2016 14:31:05 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>20160902.315</td></tr><tr><td>App uptime</td><td>16035.35</td></tr><tr><td>Build</td><td>315</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Raphaels iPhone 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>74% Unplugged</td></tr><tr><td>Memory free</td><td>87 MB / 2643 MB</td></tr><tr><td>Disk free</td><td>2779 MB / 56981 MB</td></tr><tr><td>Network IP</td><td>10.161.57.72</td></tr></table>

 [Link to buddybuild feedback from build 315](https://dashboard.buddybuild.com/apps/57a305cb34a9450100595b71/feedback?fid=57c98d291fa6270100915537&bnum=315)

**Comment by bonkey** [comment]
Might be related to updating UI in background thread.

**Comment by artdaw** [comment]
Not reproduced
