### ISSUE TITLE
raphael.koch@zalando.de on build #345: Got this error after selecting the billing address

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#212]
Feedback from raphael.koch@zalando.de : Got this error after selecting the billing address 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57a305cb34a9450100595b71/57ccdfb0284b7f01006b3e5f/a5d5cbd0-533c-434a-8b38-28e360637b94.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Sep 07 2016 08:43:57 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>20160905.345</td></tr><tr><td>App uptime</td><td>1054.744</td></tr><tr><td>Build</td><td>345</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Raphaels iPhone 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>95% Unplugged</td></tr><tr><td>Memory free</td><td>97 MB / 2568 MB</td></tr><tr><td>Disk free</td><td>2292 MB / 56981 MB</td></tr><tr><td>Network IP</td><td>10.161.57.89</td></tr></table>

 [Link to buddybuild feedback from build 345](https://dashboard.buddybuild.com/apps/57a305cb34a9450100595b71/feedback?fid=57cfd34d38c63c01006b4f7e&bnum=345)

**Comment by ahmed-shehata** [comment]
Fixed (cc @hani-ibrahim)
