### ISSUE TITLE
raphael.koch@zalando.de on build #345: € sign has to be behind the numbers: 209,95 €

Below Total…

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#213]
Feedback from raphael.koch@zalando.de : € sign has to be behind the numbers: 209,95 €

Below Total the following sentence has to be displayed: '(inkl. MwST.)'
in a smaller font

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57a305cb34a9450100595b71/57ccdfb0284b7f01006b3e5f/a15ae03d-6a3d-4efd-aed4-7c1047a72c01.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Sep 07 2016 08:57:57 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>20160905.345</td></tr><tr><td>App uptime</td><td>1896.113</td></tr><tr><td>Build</td><td>345</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Raphaels iPhone 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>90% Unplugged</td></tr><tr><td>Memory free</td><td>69 MB / 3208 MB</td></tr><tr><td>Disk free</td><td>2332 MB / 56981 MB</td></tr><tr><td>Network IP</td><td>10.161.57.89</td></tr></table>

 [Link to buddybuild feedback from build 345](https://dashboard.buddybuild.com/apps/57a305cb34a9450100595b71/feedback?fid=57cfd695d24cbb0100872519&bnum=345)

**Comment by artdaw** [comment]
As it is described in Wikipedia https://en.wikipedia.org/wiki/Linguistic_issues_concerning_the_euro in English euro sign is placed before a number. That is why you see it like this. We use standard formatter for currency.

**Comment by artdaw** [comment]
The '(inkl. MwST.)' sentence is fixed in #42
