### ISSUE TITLE
Random application crash

### ISSUE THREAD

**Issue by artdaw** [zalando-incubator/atlas-ios#229]
It looks like we have a problem with random application crashes, maybe connected with `viewState` in `CheckoutSummaryViewController` which is configured on the background thread instead of main: https://github.com/zalando-incubator/atlas-ios/blob/6a05459e5d01c64fd37b3cccce30f70f35facd76/AtlasUI/AtlasUI/CheckoutSummaryViewController.swift#L13.

**Comment by bonkey** [comment]
@hani-ibrahim claims that fixed issue related to this line of code.
