### ISSUE TITLE
Incorrect authorization token breaks flow

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#255]
When authorization token is invalid and backend responds with 401 Unauthorised the flow in UI breaks.

Maybe 401 needs to be handled differently or backend should introduce 403 case?

To quickly reproduce: first login with mock service (it will create token with `TOKEN` value), then switch to real backend.

**Comment by artdaw** [comment]
Things to do in this issue:

- [ ] Remove authorization token in GetArticle request cause it is not needed by API
- [ ] Fix "Checkout with Zalando button"
