### ISSUE TITLE
Unify all success/failure blocks in AtlasUI

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#292]
There're a lot of

```
client.request { result
  switch result {
    .failure(let error) {}
    .success(let data) {}
  }
}
```

code blocks.

Would be great to unify them.

Maybe by using NSOperations with internal NSOperation for UI (@hani-ibrahim has some know-how about it), maybe by using promises-like approach, let say like signals in [Interstellar](https://github.com/JensRavens/Interstellar)

**Comment by hani-ibrahim** [comment]
fixed in 
https://github.com/zalando-incubator/atlas-ios/issues/304
&
https://github.com/zalando-incubator/atlas-ios/issues/301
