### ISSUE TITLE
Error handling: Big "oops" view for fatal errors

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#328]
If an error cannot be handled, big "oops" message is shown with "OK" button which closes full checkout controller.

![complete error](https://cloud.githubusercontent.com/assets/39100/18867287/edd5564e-84a3-11e6-88e2-73755a6321ac.jpg)

**Comment by bonkey** [comment]
@hani-ibrahim Is it implemented in #304?

**Comment by hani-ibrahim** [comment]
no, the checkout will be dismissed and a popup will appear

**Comment by bonkey** [comment]
Hm, isn't it making a user a bit more lost?

**Comment by hani-ibrahim** [comment]
All the errors now and just Oops, that's why we have other tickets for these errors types

**Comment by hani-ibrahim** [comment]
but for your question, yes
currently the user doesn't understand anything and that should be fixed when we proper handle the errors
