### ISSUE TITLE
Form validation: All regex patterns should have meaningful messages

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#330]
Zipcode message is clear. City must explain better what's wrong and all `Pattern`s as well.

Just best with:

```
enum FormValidator {
  case Pattern(pattern: String, message: String)
}
```

https://github.com/zalando-incubator/atlas-ios/blob/46adfeb7845abbae893383786bc1ec73c96ebc4c/AtlasUI/AtlasUI/Utils/FormValidator.swift#L12

![screen shot 2016-09-27 at 11 36 47](https://cloud.githubusercontent.com/assets/39100/18867967/b22ea6f6-84a6-11e6-9afe-75e94e1b6b18.png)

**Comment by hani-ibrahim** [comment]
@bonkey but remember that the regex would be retuned from the API. which could be tricky to add a message for it

**Comment by bonkey** [comment]
But why not have the message (localized string key, actually) in API? And API is not going to be updated soon, so let's fix it the simple way for now.
