### ISSUE TITLE
Add screenshot functionality to the Demo App

### ISSUE THREAD

**Issue by artdaw** [zalando-incubator/atlas-ios#337]
Our Bug Bashing testers should be able to submit UI bugs quickly.
Add screenshot functionality to the Demo App:
when a tester makes a screenshot new email with pre filled To address and subject should be created. Screenshot should be as an attachment.

**Comment by artdaw** [comment]
Our Bug Bushing testers should be able to submit UI bugs quickly.
Add screenshot functionality to the Demo App:
when a tester makes a screenshot new email with pre filled To address and subject should be created. Screenshot should be as an attachment.

**Comment by bonkey** [comment]
Related #338
