### ISSUE TITLE
Add lookback.io into Demo app

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#338]
It's pretty easy to [manually add](https://lookback.io/learn/ios-sdk/get-started) it and required frameworks, and init with token: `yxHNcPapi4XecJDit`

It should help us to gather feedback during bug bashing sessions.

**Comment by bonkey** [comment]
Questions to answer:
1. How to identify user?
2. How to highlight important part of whole recording

**Comment by bonkey** [comment]
Record yourself to create simple introduction how does it work for testers

**Comment by ahmed-shehata** [comment]
It's. Just. Amazing.
