### ISSUE TITLE
Add language switcher in Demo App

### ISSUE THREAD

**Issue by ahmed-shehata** [zalando-incubator/atlas-ios#344]

**Comment by bonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing 1,2,3](https://trello.com/c/xVV7sOEW/1-testing-1-2-3)

**Comment by ahmed-shehata** [comment]
Should this be merged with #355 ?

**Comment by bonkey** [comment]
Why? Language and environment are different things
