### ISSUE TITLE
Implement data connection retrying

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#37]
If connection fails from connectivity – try few times again. Could be some adaptive algorithm: 2*N seconds for next try and 5 tries.

**Comment by hani-ibrahim** [comment]
Not sure about this, it's not a chatting app. 
IMHO, we should not retry calls for payments stuff. I also thing this is not happening in the fashion store app

**Comment by bonkey** [comment]
Maybe not automatically, but on "Retry" button for some cases

**Comment by bonkey** [comment]
If we need it, we would notice it and create a new issue.
