### ISSUE TITLE
Empty address list: unequal rows height

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#389]
![simulator screen shot 4 oct 2016 11 32 21](https://cloud.githubusercontent.com/assets/39100/19069245/5262d974-8a26-11e6-8de2-40c6475bef53.png)

**Comment by hani-ibrahim** [comment]
Can't reproduce 😖

**Comment by hani-ibrahim** [comment]
@bonkey I guess I know the problem. 
If this was on simulator and you decrease the simulator size (cmd+2 OR cmd+3) then this could happen because the line is probably 1 px and it can't be interpreted on the smaller scale simulator.
Then it's not an issue

**Comment by bonkey** [comment]
Right, of course! It happens often. Probably in the rush of bug hunting I didn't thought about it.
