### ISSUE TITLE
Remove links from ToC page

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#403]
### Message from Atlas Testing sent on 2016-10-05 13:39:48 UTC

> I am able to browse the shop from the terms and conditions page
> ---
> 
> iPhone 6 Plus
> iPhone OS 10.0.1
> 
> Sent from my iPhone
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/398497/feedback/632800](https://rink.hockeyapp.net/manage/apps/398497/feedback/632800)

**Comment by ahmed-shehata** [comment]
Related to TOC header

**Comment by bonkey** [comment]
Fixed in #498
