### ISSUE TITLE
Can't accept payment in webvew (probably because of wrong birth date)

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#407]
### Message from Atlas Testing sent on 2016-10-05 13:46:16 UTC

> I am trying to click Weiter but nothing happens and no explanation. Probably because invalid birth date
> ---
> 
> iPhone 6 Plus
> iPhone OS 10.0.1
> 
> Sent from my iPhone
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/398497/feedback/632808](https://rink.hockeyapp.net/manage/apps/398497/feedback/632808)

**Comment by bonkey** [comment]
![no-weiter-in-payment](https://cloud.githubusercontent.com/assets/39100/19150023/0ff275fe-8bc5-11e6-8ad8-dfc961224ef8.jpg)

**Comment by pc-alves** [comment]
Payment Method selection page now displays an error when an invalid date is selected.

![screen shot 2017-01-17 at 10 47 19](https://cloud.githubusercontent.com/assets/20203246/22015545/d328d47c-dca2-11e6-8002-9052c15cf528.png)
