### ISSUE TITLE
After selecting PayPal all my addresses disappeared -- Balazs

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#409]
### Message from Atlas Testing sent on 2016-10-05 13:49:31 UTC###

> After selecting PayPal all my addresses disappeared -- Balazs
> 
> 
> -------------
> iPhone 6 Plus
> iPhone OS 10.0.1
> 
> 
> 
> 
> 
> Sent from my iPhone

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/398497/feedback/632814](https://rink.hockeyapp.net/manage/apps/398497/feedback/632814)

**Comment by ahmed-shehata** [comment]
Maybe related to "Selecting payment twice wipes the checkout object"

**Comment by bonkey** [comment]
See #414
