### ISSUE TITLE
Screen ends up with error message + infinite loading only

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#411]
### Message from Atlas Testing sent on 2016-10-05 13:55:00 UTC###

> No idea what this is
> 
> 
> -------------
> iPhone 6
> iPhone OS 9.3.1

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/398497/feedback/632819](https://rink.hockeyapp.net/manage/apps/398497/feedback/632819)

**Comment by ahmed-shehata** [comment]
1 - Find out what is the exact scenario (network, blocking, etc.. ?)
2 - Handle if special case (in this case blocking error OR handle refresh somehow)

**Comment by bonkey** [comment]
![spinner-error-only](https://cloud.githubusercontent.com/assets/39100/19150134/90cb12ee-8bc5-11e6-966b-eab3d979ab07.jpg)
