### ISSUE TITLE
Feedback 'Bug Bashing Alexander Yastrebov'

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#412]
### Message from Atlas Testing sent on 2016-10-05 13:56:53 UTC###

> Before clicking place order disable wifi.
> App reports success, but should report network failure
> -------------
> iPhone 6
> iPhone OS 9.3.2

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/398497/feedback/632822](https://rink.hockeyapp.net/manage/apps/398497/feedback/632822)

**Comment by ahmed-shehata** [comment]
Due to fake order
