### ISSUE TITLE
Select your address then while loading click around a lot and no address will be selected

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#413]
### Message from Atlas Testing sent on 2016-10-05 13:57:17 UTC###

> Select your address then while loading click around a lot and no address will be selected
> -- Balazs
> 
> -------------
> iPhone 6 Plus
> iPhone OS 10.0.1
> 
> 
> 
> 
> 
> Sent from my iPhone

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/398497/feedback/632823](https://rink.hockeyapp.net/manage/apps/398497/feedback/632823)

**Comment by bonkey** [comment]
![no-address-selected](https://cloud.githubusercontent.com/assets/39100/19150151/abb1474a-8bc5-11e6-9b95-629e8cd81a07.jpg)

**Comment by hani-ibrahim** [comment]
most probably with is related to how the `checkoutFailed` is handled https://github.com/zalando-incubator/atlas-ios/issues/474

**Comment by bonkey** [comment]
Will be closed with #474
