### ISSUE TITLE
Feedback 'Bug Bashing. Billing address'

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#415]
### Message from Atlas Testing sent on 2016-10-05 14:02:01 UTC###

> Add new billing address verify that new billing address will be automatically added as an shipping address which should not be allowed 
> 
> -------------
> iPhone SE
> iPhone OS 9.3

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/398497/feedback/632830](https://rink.hockeyapp.net/manage/apps/398497/feedback/632830)

**Comment by ahmed-shehata** [comment]
Not a bug
