### ISSUE TITLE
One-size item should be marked as it, not specific size

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#424]
### Message from Atlas Testing sent on 2016-10-05 15:27:18 UTC###

> It is telling me size 55 without any option before to choose a size. Should be one size
> 
> Alex kaufhold 
> -------------
> iPhone 6
> iPhone OS 9.3.3

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/398497/feedback/632886](https://rink.hockeyapp.net/manage/apps/398497/feedback/632886)

**Comment by ahmed-shehata** [comment]
We need to check if "unavailable" sizes are still present in this specific case @hani-ibrahim

**Comment by bonkey** [comment]
We should check with backend if they provide correct label for the size and how it should be handled: on their or our side.

**Comment by bonkey** [comment]
This is correct behaviour for this article.
