### ISSUE TITLE
Fix zip validation rule

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#428]
### Message from Atlas Testing sent on 2016-10-05 15:47:14 UTC###

> After using wrong postcode (using a space - see previous bug mail "123 4")) and choosing it as both shipping & billing address both address will removed after some seconds. - but addresses are still saved.
> 
> // Franzi
> 
> 
> -------------
> iPhone 6
> iPhone OS 9.3.2

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/398497/feedback/632905](https://rink.hockeyapp.net/manage/apps/398497/feedback/632905)

**Comment by ahmed-shehata** [comment]
Regex check @hani-ibrahim
