### ISSUE TITLE
After resetting password, user is directed to the login screen

### ISSUE THREAD

**Issue by ahmed-shehata** [zalando-incubator/atlas-ios#443]

**Comment by bonkey** [comment]
@ahmed-shehata what's the expected outcome?

**Comment by ahmed-shehata** [comment]
User should see "Congrats, password resetted successfully"

**Comment by bonkey** [comment]
So, needs to be checked again, as it's also expected implementation.

**Comment by hani-ibrahim** [comment]
There is a message displayed for 2-3 seconds saying that an email is already sent.

![img_2662](https://cloud.githubusercontent.com/assets/5626418/19555113/bfc23df6-96bb-11e6-87d5-115198f35510.PNG)
