### ISSUE TITLE
Unexpected webview exit with unclassified error

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#453]
After going to payment page and searching for some random items, then UI returns back with this error:

![img_0013](https://cloud.githubusercontent.com/assets/39100/19150905/e79ac0d4-8bc9-11e6-926c-b27634dead28.PNG)

**Comment by bonkey** [comment]
Related #403

**Comment by hani-ibrahim** [comment]
fixed in #446
