### ISSUE TITLE
Bug: If user cancels login after picking size, spinner remains on screen forever

### ISSUE THREAD

**Issue by ahmed-shehata** [zalando-incubator/atlas-ios#461]
![simulator screen shot oct 7 2016 11 03 03 am](https://cloud.githubusercontent.com/assets/4982099/19184487/abc247d0-8c7d-11e6-821c-8ab41c52e06b.png)

**Comment by bonkey** [comment]
@hani-ibrahim If I remember correctly it's long befoe rebuilt, and could be closed.

**Comment by hani-ibrahim** [comment]
yeah it's way too old
