### ISSUE TITLE
Display the item price in the checkout summary as the total price shown include taxes

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#502]
Price of item in size selector is different than total (due to tax):

![img_2666](https://cloud.githubusercontent.com/assets/39100/19601192/86e35b3a-97a8-11e6-99d0-3271d6b84579.PNG)

![img_2667](https://cloud.githubusercontent.com/assets/39100/19601193/870d28fc-97a8-11e6-9bb4-4bd783e13977.PNG)

**Comment by hani-ibrahim** [comment]
@bonkey after taking with Raphael and Fabio, and found that the tax is already included but the mismatch is because the prices on staging are out of sync with prices on live.
Switching the app to live version fixes the problem and the prices are the same.
.
Still I found the most critical bug 😕  😖
