### ISSUE TITLE
Check PayPal

### ISSUE THREAD

**Issue by hani-ibrahim** [zalando-incubator/atlas-ios#534]

**Comment by bonkey** [comment]
https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_server.md#retrieve-customer-information

**Comment by hani-ibrahim** [comment]
Checking PayPal integration, I see that most of the work is done on the backend side

**Fetching User details:**
- We can fetch the user details like address and use it in the order. But this is done on the server. We just need the user to accept the consent on the mobile and then the server needs to get access token and request the customer details.
- Here is a technical document for how this integration should look like: https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/profile_sharing_server.md

**Using PayPal iOS SDK:**
- We can use the iOS SDK to obtain the user's authorized consent and then the server side will still have to fetch the profile details.
- The SDK can also be used to do a payment by which we can open the PayPal view with an optional shipping address and the user can choose another address from his PayPal account if he wants.

One thing is that there is no way in the iOS SDK that we can get the new address that the user chose in the PayPal screen or validate it. This could be done by the server. But then I don't see the benefit of using PayPal iOS SDK.

**Comment by bonkey** [comment]
Copied to [wiki](https://github.com/zalando-incubator/atlas-ios/wiki/Apple-Pay-Integration)
