### ISSUE TITLE
Guest Checkout remaining things

### ISSUE THREAD

**Issue by hani-ibrahim** [zalando-incubator/atlas-ios#594]
1- Check the title of the submit button "Checkout as Guest" 
2- Check paying with credit card

**Comment by bonkey** [comment]
@hani-ibrahim Would help in automated release notes to have them as separated issues with meaningful titles

**Comment by hani-ibrahim** [comment]
Actually I may delete this ticket, they are just somethings in my mind that I want to check. I created a ticket not to forget them

**Comment by hani-ibrahim** [comment]
@bonkey I fixed the first one (title) in another PR
And created another ticket for the second issue
https://github.com/zalando-incubator/atlas-ios/projects/8#card-1057271
