### ISSUE TITLE
Discuss how we should handle the response of the `address_check` endpoint

### ISSUE THREAD

**Issue by hani-ibrahim** [zalando-incubator/atlas-ios#611]
The check address endpoint returns value from 3 which are "CORRECT", "NORMALIZED", "NOT_CORRECT"

Currently `CORRECT` and `NORMALIZED` are handled the same way by just using the address that the user entered, and `NOT_CORRECT` display error to the user

The question is, for the case `NORMALIZED` ... what should be done? display the new option to the user and allow him to choose or what?

**Comment by bonkey** [comment]
Handle `NORMALIZED` correctly (create a new ticket)

**Comment by bonkey** [comment]
Follows in #671
