### ISSUE TITLE
investigate `WebKitErrorDomain` in `PaymentViewController`

### ISSUE THREAD

**Issue by hani-ibrahim** [zalando-incubator/atlas-ios#616]

**Comment by hani-ibrahim** [comment]
@bonkey After investigation, Sometimes I'm getting the bellow error from the webView when we return false from `shouldStartLoadWith` method
```
(lldb) po error
Error Domain=WebKitErrorDomain Code=102 "Frame load interrupted" UserInfo={NSErrorFailingURLStringKey=http://de.zalando.atlas.atlascheckoutdemo/redirect, NSLocalizedDescription=Frame load interrupted, NSErrorFailingURLKey=http://de.zalando.atlas.atlascheckoutdemo/redirect}
```

So we need to keep the `isWebKitError` in the PaymentViewController

**Comment by bonkey** [comment]
Then maybe we should check additionally `NSErrorFailingURLStringKey`?

**Comment by hani-ibrahim** [comment]
@bonkey but what would be the value in this case? may be check on code better?

**Comment by bonkey** [comment]
I dunno, I just noticed it in your paste:

```
UserInfo={NSErrorFailingURLStringKey=http://de.zalando.atlas.atlascheckoutdemo/redirect,
NSLocalizedDescription=Frame load interrupted,
NSErrorFailingURLKey=http://de.zalando.atlas.atlascheckoutdemo/redirect}
```

**Comment by bonkey** [comment]
Put a comment into body of current `isWebKitError` why it's only about `WebKitErrorDomain` and rename it accordingly to the purpose
