### ISSUE TITLE
AtlasUI shouldn't show error about X-Sales-Channel (and others low-level)

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#629]
![upload](https://cloud.githubusercontent.com/assets/39100/21221056/30671618-c2bc-11e6-938e-848a9dccbc1c.png)

**Comment by bonkey** [comment]
Verify by removing `X-Sales-Channel` from the code.

**Comment by hani-ibrahim** [comment]
@bonkey check now and found the below image, so it should be fixed 

![simulator screen shot 9 feb 2017 4 32 46 pm](https://cloud.githubusercontent.com/assets/5626418/22790136/850a51bc-eee5-11e6-8db5-768c96b43751.png)
