### ISSUE TITLE
There should not be delivery date displayed if prepayment method is selected

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#661]
Could require backend implementation

**Comment by hani-ibrahim** [comment]
@bonkey taking with Pedro, It's actually a company problem that the coast team return the delivery dates in this endpoint and we checked the website and we found that the address is displayed there 
![screen shot 2017-02-06 at 4 50 00 pm](https://cloud.githubusercontent.com/assets/5626418/22654300/a48e58d6-ec8c-11e6-867a-c2a5e6380f1f.png)

**Comment by hani-ibrahim** [comment]
@bonkey after talking with Amr, we will close it since it's a known problem on the web too
