### ISSUE TITLE
Add main thread guard for UIKit operations

### ISSUE THREAD

**Issue by bonkey** [zalando-incubator/atlas-ios#664]
Something like or just a direct copy:

https://github.com/olddonkey/ODUIThreadGuard/blob/master/ODUIThreadGuard/ODUIThreadGuard.swift

**Comment by bonkey** [comment]
How about it, @hani-ibrahim?

**Comment by hani-ibrahim** [comment]
uhm, it worth a try.

**Comment by bonkey** [comment]
No use for now
