### ISSUE TITLE
Check OneSky Translation Service

### ISSUE THREAD

**Issue by hani-ibrahim** [zalando-incubator/atlas-ios#691]
https://www.oneskyapp.com
May be this one would be good?
It's free with unlimited words, however the free version is only for 3 contributors

**Comment by bonkey** [comment]
Pulled to Tasks in Tech Debt.

**Comment by bonkey** [comment]
Short review:

**Pros:**

1. No limits for amount of translations
1. Free tier with 3 collaborators
1. Provides separated dictionary of common phrases
1. Simple way of updating translations: just upload or download everything, through UI or API

**Cons:**

1. Complex and slow UI

**Other notable features**

1. Simple [API for upload/download translations](https://github.com/onesky/api-documentation-platform/blob/master/resources/translation.md#export---export-translations-in-files) with [multiple libraries](https://www.oneskyapp.com/how-it-works/integrations-plugins/) to integrate, including [ruby]()  for calypso.rb
1. [Dynamic translations library](https://github.com/onesky/plugin-ios-ota). Probably not worth it to include such external closed-source library for so few and not often changed translations, but in case it's needed – it's there.
1. Theoretically [nice Xcode plugin](https://github.com/onesky/plugin-xcode) for automated uploads/downloads. Unfortunately, not updated for long and totally not compatible with current version
1. Nice feature to extract translations from screenshots. Not sure if it would work everywhere, thou.

**Comment by bonkey** [comment]
As a reference, other similar services: http://www.businessofapps.com/top-app-localization-tools/

**Comment by hani-ibrahim** [comment]
👍 
I added it here https://github.com/zalando-incubator/atlas-ios/wiki/Translations
